2013-08-16 21:42:21 Error: [MissingActionException] Action AppController::index() could not be found.
Exception Attributes: array (
  'controller' => 'AppController',
  'action' => 'index',
)
Request URL: /call4pizza-reservation/app/
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(AppController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\call4pizza-reservation\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2013-08-23 22:32:06 Error: [MissingActionException] Action AppController::index() could not be found.
Exception Attributes: array (
  'controller' => 'AppController',
  'action' => 'index',
)
Request URL: /call4pizza-reservation/app/
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(AppController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\call4pizza-reservation\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2013-08-24 00:25:34 Error: [MissingViewException] View file "C:\xampp\htdocs\call4pizza-reservation\app\View\Meals\view.ctp" is missing.
Exception Attributes: array (
  'file' => 'C:\\xampp\\htdocs\\call4pizza-reservation\\app\\View\\Meals\\view.ctp',
)
Request URL: /call4pizza-reservation/meals/view/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Controller\Controller.php(952): View->render(NULL, NULL)
#2 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(194): Controller->render()
#3 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(MealsController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\call4pizza-reservation\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-08-24 00:25:48 Error: [MissingActionException] Action AppController::meals() could not be found.
Exception Attributes: array (
  'controller' => 'AppController',
  'action' => 'meals',
)
Request URL: /call4pizza-reservation/app/meals/view/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(AppController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\call4pizza-reservation\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2013-08-24 00:28:49 Error: [MissingActionException] Action AppController::meal() could not be found.
Exception Attributes: array (
  'controller' => 'AppController',
  'action' => 'meal',
)
Request URL: /call4pizza-reservation/app/meal/view/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(AppController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\call4pizza-reservation\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2013-08-24 00:28:57 Error: [MissingControllerException] Controller class MealController could not be found.
Exception Attributes: array (
  'class' => 'MealController',
  'plugin' => NULL,
)
Request URL: /call4pizza-reservation/meal/view/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2013-08-24 00:29:13 Error: [MissingViewException] View file "C:\xampp\htdocs\call4pizza-reservation\app\View\Meals\view.ctp" is missing.
Exception Attributes: array (
  'file' => 'C:\\xampp\\htdocs\\call4pizza-reservation\\app\\View\\Meals\\view.ctp',
)
Request URL: /call4pizza-reservation/meals/view/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Controller\Controller.php(952): View->render(NULL, NULL)
#2 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(194): Controller->render()
#3 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(MealsController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\call4pizza-reservation\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-08-24 00:37:53 Error: Fatal Error (4): syntax error, unexpected '{', expecting '(' in [C:\xampp\htdocs\call4pizza-reservation\app\Model\Meal.php, line 3]
2013-08-24 00:37:53 Error: [FatalErrorException] syntax error, unexpected '{', expecting '('
Request URL: /call4pizza-reservation/meals/view/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 3)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 3, Array)
#2 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 3, Array)
#3 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-08-24 00:38:28 Error: Fatal Error (4): syntax error, unexpected '{', expecting '(' in [C:\xampp\htdocs\call4pizza-reservation\app\Model\Meal.php, line 3]
2013-08-24 00:38:28 Error: [FatalErrorException] syntax error, unexpected '{', expecting '('
Request URL: /call4pizza-reservation/meals/view/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 3)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 3, Array)
#2 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 3, Array)
#3 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-08-24 00:38:28 Error: Fatal Error (4): syntax error, unexpected '{', expecting '(' in [C:\xampp\htdocs\call4pizza-reservation\app\Model\Meal.php, line 3]
2013-08-24 00:38:28 Error: [FatalErrorException] syntax error, unexpected '{', expecting '('
Request URL: /call4pizza-reservation/meals/view/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 3)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 3, Array)
#2 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 3, Array)
#3 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-08-24 00:40:10 Error: Fatal Error (4): syntax error, unexpected '{', expecting '(' in [C:\xampp\htdocs\call4pizza-reservation\app\Model\Meal.php, line 3]
2013-08-24 00:40:10 Error: [FatalErrorException] syntax error, unexpected '{', expecting '('
Request URL: /call4pizza-reservation/meals/view/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 3)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 3, Array)
#2 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 3, Array)
#3 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-08-24 00:40:11 Error: Fatal Error (4): syntax error, unexpected '{', expecting '(' in [C:\xampp\htdocs\call4pizza-reservation\app\Model\Meal.php, line 3]
2013-08-24 00:40:11 Error: [FatalErrorException] syntax error, unexpected '{', expecting '('
Request URL: /call4pizza-reservation/meals/view/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 3)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 3, Array)
#2 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 3, Array)
#3 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-08-24 00:40:11 Error: Fatal Error (4): syntax error, unexpected '{', expecting '(' in [C:\xampp\htdocs\call4pizza-reservation\app\Model\Meal.php, line 3]
2013-08-24 00:40:11 Error: [FatalErrorException] syntax error, unexpected '{', expecting '('
Request URL: /call4pizza-reservation/meals/view/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 3)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 3, Array)
#2 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 3, Array)
#3 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-08-24 00:40:12 Error: Fatal Error (4): syntax error, unexpected '{', expecting '(' in [C:\xampp\htdocs\call4pizza-reservation\app\Model\Meal.php, line 3]
2013-08-24 00:40:12 Error: [FatalErrorException] syntax error, unexpected '{', expecting '('
Request URL: /call4pizza-reservation/meals/view/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 3)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 3, Array)
#2 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 3, Array)
#3 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-08-24 00:40:12 Error: Fatal Error (4): syntax error, unexpected '{', expecting '(' in [C:\xampp\htdocs\call4pizza-reservation\app\Model\Meal.php, line 3]
2013-08-24 00:40:12 Error: [FatalErrorException] syntax error, unexpected '{', expecting '('
Request URL: /call4pizza-reservation/meals/view/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 3)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 3, Array)
#2 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 3, Array)
#3 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-08-24 00:40:12 Error: Fatal Error (4): syntax error, unexpected '{', expecting '(' in [C:\xampp\htdocs\call4pizza-reservation\app\Model\Meal.php, line 3]
2013-08-24 00:40:12 Error: [FatalErrorException] syntax error, unexpected '{', expecting '('
Request URL: /call4pizza-reservation/meals/view/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 3)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 3, Array)
#2 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 3, Array)
#3 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-08-24 00:40:12 Error: Fatal Error (4): syntax error, unexpected '{', expecting '(' in [C:\xampp\htdocs\call4pizza-reservation\app\Model\Meal.php, line 3]
2013-08-24 00:40:12 Error: [FatalErrorException] syntax error, unexpected '{', expecting '('
Request URL: /call4pizza-reservation/meals/view/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 3)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 3, Array)
#2 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 3, Array)
#3 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-08-24 00:42:22 Error: Fatal Error (4): syntax error, unexpected '{', expecting '(' in [C:\xampp\htdocs\call4pizza-reservation\app\Model\Meal.php, line 4]
2013-08-24 00:42:22 Error: [FatalErrorException] syntax error, unexpected '{', expecting '('
Request URL: /call4pizza-reservation/meals/view/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 4)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 4, Array)
#2 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 4, Array)
#3 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-08-24 00:42:23 Error: Fatal Error (4): syntax error, unexpected '{', expecting '(' in [C:\xampp\htdocs\call4pizza-reservation\app\Model\Meal.php, line 4]
2013-08-24 00:42:23 Error: [FatalErrorException] syntax error, unexpected '{', expecting '('
Request URL: /call4pizza-reservation/meals/view/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 4)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 4, Array)
#2 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 4, Array)
#3 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-08-24 00:42:23 Error: Fatal Error (4): syntax error, unexpected '{', expecting '(' in [C:\xampp\htdocs\call4pizza-reservation\app\Model\Meal.php, line 4]
2013-08-24 00:42:23 Error: [FatalErrorException] syntax error, unexpected '{', expecting '('
Request URL: /call4pizza-reservation/meals/view/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 4)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 4, Array)
#2 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 4, Array)
#3 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-08-24 00:43:50 Error: Fatal Error (4): syntax error, unexpected '{', expecting '(' in [C:\xampp\htdocs\call4pizza-reservation\app\Model\Order.php, line 3]
2013-08-24 00:43:50 Error: [FatalErrorException] syntax error, unexpected '{', expecting '('
Request URL: /call4pizza-reservation/meals/view/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 3)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 3, Array)
#2 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 3, Array)
#3 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-08-24 00:43:51 Error: Fatal Error (4): syntax error, unexpected '{', expecting '(' in [C:\xampp\htdocs\call4pizza-reservation\app\Model\Order.php, line 3]
2013-08-24 00:43:51 Error: [FatalErrorException] syntax error, unexpected '{', expecting '('
Request URL: /call4pizza-reservation/meals/view/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 3)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 3, Array)
#2 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 3, Array)
#3 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-08-24 00:43:52 Error: Fatal Error (4): syntax error, unexpected '{', expecting '(' in [C:\xampp\htdocs\call4pizza-reservation\app\Model\Order.php, line 3]
2013-08-24 00:43:52 Error: [FatalErrorException] syntax error, unexpected '{', expecting '('
Request URL: /call4pizza-reservation/meals/view/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 3)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 3, Array)
#2 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 3, Array)
#3 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-08-24 00:44:25 Error: Fatal Error (4): syntax error, unexpected '{', expecting '(' in [C:\xampp\htdocs\call4pizza-reservation\app\Model\IngredientMeal.php, line 3]
2013-08-24 00:44:25 Error: [FatalErrorException] syntax error, unexpected '{', expecting '('
Request URL: /call4pizza-reservation/meals/view/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 3)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 3, Array)
#2 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 3, Array)
#3 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-08-24 00:44:49 Error: [MissingTableException] Table ingredient_meals for model IngredientMeal was not found in datasource default.
Exception Attributes: array (
  'table' => 'ingredient_meals',
  'class' => 'IngredientMeal',
  'ds' => 'default',
)
Request URL: /call4pizza-reservation/meals/view/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Model\Model.php(3247): Model->setSource('ingredient_meal...')
#1 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Model\Datasource\DboSource.php(1063): Model->getDataSource()
#2 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Model\Model.php(2700): DboSource->read(Object(Meal), Array)
#3 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Model\Datasource\DboSource.php(599): Model->find('first', Array)
#4 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Model\Model.php(799): DboSource->query('findById', Array, Object(Meal))
#5 C:\xampp\htdocs\call4pizza-reservation\app\Controller\MealsController.php(4): Model->__call('findById', Array)
#6 C:\xampp\htdocs\call4pizza-reservation\app\Controller\MealsController.php(4): Meal->findById('2')
#7 [internal function]: MealsController->view('2')
#8 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(MealsController), Array)
#9 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#10 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(MealsController), Object(CakeRequest), Object(CakeResponse))
#11 C:\xampp\htdocs\call4pizza-reservation\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2013-08-24 00:46:10 Error: [MissingTableException] Table ingredient_meals for model IngredientMeal was not found in datasource default.
Exception Attributes: array (
  'table' => 'ingredient_meals',
  'class' => 'IngredientMeal',
  'ds' => 'default',
)
Request URL: /call4pizza-reservation/meals/view/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Model\Model.php(3247): Model->setSource('ingredient_meal...')
#1 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Model\Datasource\DboSource.php(1063): Model->getDataSource()
#2 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Model\Model.php(2700): DboSource->read(Object(Meal), Array)
#3 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Model\Datasource\DboSource.php(599): Model->find('first', Array)
#4 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Model\Model.php(799): DboSource->query('findById', Array, Object(Meal))
#5 C:\xampp\htdocs\call4pizza-reservation\app\Controller\MealsController.php(4): Model->__call('findById', Array)
#6 C:\xampp\htdocs\call4pizza-reservation\app\Controller\MealsController.php(4): Meal->findById('2')
#7 [internal function]: MealsController->view('2')
#8 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(MealsController), Array)
#9 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#10 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(MealsController), Object(CakeRequest), Object(CakeResponse))
#11 C:\xampp\htdocs\call4pizza-reservation\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2013-08-24 20:32:33 Error: [MissingActionException] Action AppController::index() could not be found.
Exception Attributes: array (
  'controller' => 'AppController',
  'action' => 'index',
)
Request URL: /call4pizza-reservation/app/
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(AppController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\call4pizza-reservation\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2013-08-24 20:33:02 Error: [MissingControllerException] Controller class MealController could not be found.
Exception Attributes: array (
  'class' => 'MealController',
  'plugin' => NULL,
)
Request URL: /call4pizza-reservation/meal/view/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2013-08-24 20:33:16 Error: [MissingTableException] Table ingredient_meals for model IngredientMeal was not found in datasource default.
Exception Attributes: array (
  'table' => 'ingredient_meals',
  'class' => 'IngredientMeal',
  'ds' => 'default',
)
Request URL: /call4pizza-reservation/meals/view/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Model\Model.php(3247): Model->setSource('ingredient_meal...')
#1 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Model\Datasource\DboSource.php(1063): Model->getDataSource()
#2 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Model\Model.php(2700): DboSource->read(Object(Meal), Array)
#3 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Model\Datasource\DboSource.php(599): Model->find('first', Array)
#4 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Model\Model.php(799): DboSource->query('findById', Array, Object(Meal))
#5 C:\xampp\htdocs\call4pizza-reservation\app\Controller\MealsController.php(4): Model->__call('findById', Array)
#6 C:\xampp\htdocs\call4pizza-reservation\app\Controller\MealsController.php(4): Meal->findById('2')
#7 [internal function]: MealsController->view('2')
#8 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(MealsController), Array)
#9 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#10 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(MealsController), Object(CakeRequest), Object(CakeResponse))
#11 C:\xampp\htdocs\call4pizza-reservation\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2013-08-24 22:51:59 Error: [MissingTableException] Table meal_compositions for model MealComposition was not found in datasource default.
Exception Attributes: array (
  'table' => 'meal_compositions',
  'class' => 'MealComposition',
  'ds' => 'default',
)
Request URL: /call4pizza-reservation/meals/view/3
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Model\Model.php(3247): Model->setSource('meal_compositio...')
#1 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Model\Datasource\DboSource.php(1063): Model->getDataSource()
#2 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Model\Model.php(2700): DboSource->read(Object(Meal), Array)
#3 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Model\Datasource\DboSource.php(599): Model->find('first', Array)
#4 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Model\Model.php(799): DboSource->query('findById', Array, Object(Meal))
#5 C:\xampp\htdocs\call4pizza-reservation\app\Controller\MealsController.php(4): Model->__call('findById', Array)
#6 C:\xampp\htdocs\call4pizza-reservation\app\Controller\MealsController.php(4): Meal->findById('3')
#7 [internal function]: MealsController->view('3')
#8 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(MealsController), Array)
#9 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#10 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(MealsController), Object(CakeRequest), Object(CakeResponse))
#11 C:\xampp\htdocs\call4pizza-reservation\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2013-08-25 10:20:11 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'MealComposition.id' in 'where clause'
Request URL: /call4pizza-reservation/mealcompositions/view/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `MealCom...', Array)
#2 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('SELECT `MealCom...', Array, Array)
#3 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Model\Datasource\DboSource.php(1077): DboSource->fetchAll('SELECT `MealCom...', false)
#4 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Model\Model.php(2700): DboSource->read(Object(MealComposition), Array)
#5 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Model\Datasource\DboSource.php(594): Model->find('all', Array)
#6 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Model\Model.php(799): DboSource->query('findAllById', Array, Object(MealComposition))
#7 C:\xampp\htdocs\call4pizza-reservation\app\Controller\MealCompositionsController.php(4): Model->__call('findAllById', Array)
#8 C:\xampp\htdocs\call4pizza-reservation\app\Controller\MealCompositionsController.php(4): MealComposition->findAllById('2')
#9 [internal function]: MealCompositionsController->view('2')
#10 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(MealCompositionsController), Array)
#11 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#12 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(MealCompositionsController), Object(CakeRequest), Object(CakeResponse))
#13 C:\xampp\htdocs\call4pizza-reservation\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2013-08-25 10:21:05 Error: [MissingActionException] Action MealCompositionsController::viewmealigredients() could not be found.
Exception Attributes: array (
  'controller' => 'MealCompositionsController',
  'action' => 'viewmealigredients',
)
Request URL: /call4pizza-reservation/mealcompositions/viewmealigredients/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(MealCompositionsController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\call4pizza-reservation\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2013-08-25 10:21:28 Error: [MissingActionException] Action MealCompositionsController::viewMealIgredients() could not be found.
Exception Attributes: array (
  'controller' => 'MealCompositionsController',
  'action' => 'viewMealIgredients',
)
Request URL: /call4pizza-reservation/mealcompositions/viewMealIgredients/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(MealCompositionsController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\call4pizza-reservation\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2013-08-25 10:21:41 Error: [MissingViewException] View file "C:\xampp\htdocs\call4pizza-reservation\app\View\MealCompositions\view_meal_ingredients.ctp" is missing.
Exception Attributes: array (
  'file' => 'C:\\xampp\\htdocs\\call4pizza-reservation\\app\\View\\MealCompositions\\view_meal_ingredients.ctp',
)
Request URL: /call4pizza-reservation/mealcompositions/viewMealIngredients/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Controller\Controller.php(952): View->render(NULL, NULL)
#2 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(194): Controller->render()
#3 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(MealCompositionsController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\call4pizza-reservation\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-08-25 10:22:15 Error: [MissingViewException] View file "C:\xampp\htdocs\call4pizza-reservation\app\View\MealCompositions\view.ctp" is missing.
Exception Attributes: array (
  'file' => 'C:\\xampp\\htdocs\\call4pizza-reservation\\app\\View\\MealCompositions\\view.ctp',
)
Request URL: /call4pizza-reservation/mealcompositions/view/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Controller\Controller.php(952): View->render(NULL, NULL)
#2 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(194): Controller->render()
#3 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(MealCompositionsController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\call4pizza-reservation\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-08-25 10:27:36 Error: [MissingViewException] View file "C:\xampp\htdocs\call4pizza-reservation\app\View\MealCompositions\viewmealingredients.ctp" is missing.
Exception Attributes: array (
  'file' => 'C:\\xampp\\htdocs\\call4pizza-reservation\\app\\View\\MealCompositions\\viewmealingredients.ctp',
)
Request URL: /call4pizza-reservation/mealcompositions/viewmealingredients/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Controller\Controller.php(952): View->render(NULL, NULL)
#2 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(194): Controller->render()
#3 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(MealCompositionsController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\call4pizza-reservation\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-08-25 10:27:51 Error: [MissingViewException] View file "C:\xampp\htdocs\call4pizza-reservation\app\View\MealCompositions\view_meal_ingredients.ctp" is missing.
Exception Attributes: array (
  'file' => 'C:\\xampp\\htdocs\\call4pizza-reservation\\app\\View\\MealCompositions\\view_meal_ingredients.ctp',
)
Request URL: /call4pizza-reservation/mealcompositions/viewMealIngredients/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Controller\Controller.php(952): View->render(NULL, NULL)
#2 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(194): Controller->render()
#3 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(MealCompositionsController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\call4pizza-reservation\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-08-25 10:28:53 Error: [MissingViewException] View file "C:\xampp\htdocs\call4pizza-reservation\app\View\MealCompositions\view_meal_ingredients.ctp" is missing.
Exception Attributes: array (
  'file' => 'C:\\xampp\\htdocs\\call4pizza-reservation\\app\\View\\MealCompositions\\view_meal_ingredients.ctp',
)
Request URL: /call4pizza-reservation/mealcompositions/viewMealIngredients/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Controller\Controller.php(952): View->render(NULL, NULL)
#2 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(194): Controller->render()
#3 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(MealCompositionsController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\call4pizza-reservation\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-08-25 10:29:21 Error: [MissingViewException] View file "C:\xampp\htdocs\call4pizza-reservation\app\View\MealCompositions\viewmealingredients.ctp" is missing.
Exception Attributes: array (
  'file' => 'C:\\xampp\\htdocs\\call4pizza-reservation\\app\\View\\MealCompositions\\viewmealingredients.ctp',
)
Request URL: /call4pizza-reservation/mealcompositions/viewmealingredients/2
Stack Trace:
#0 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Controller\Controller.php(952): View->render(NULL, NULL)
#2 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(194): Controller->render()
#3 C:\xampp\htdocs\call4pizza-reservation\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(MealCompositionsController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\call4pizza-reservation\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
